In [75]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\sujee\AppData\Roaming\Python\Python314\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\sujee\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sujee\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\sujee\AppData\Roaming\Python\Python314\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\sujee\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [76]:
# import pandas

In [77]:
import pandas as pd

In [78]:
pd.__version__

'3.0.6'

In [79]:
df = pd.DataFrame([11,22,33], columns=['Col_Name'])

In [80]:
data = {
    'Name' : ['Madhav', 'Vishakha', 'Lalita', 'Rishabh'],
    'Age': [16, 17, 18, 19],
    'Salary': [90000, 70000,50000,30000]
}

In [81]:
df = pd.DataFrame(data)

In [82]:
print(df)

       Name  Age  Salary
0    Madhav   16   90000
1  Vishakha   17   70000
2    Lalita   18   50000
3   Rishabh   19   30000

In [83]:
print(type(df))

<class 'pandas.DataFrame'>

In [84]:
print(df.head(1))

     Name  Age  Salary
0  Madhav   16   90000

In [85]:
df.tail(1)

      Name  Age  Salary
3  Rishabh   19   30000

In [86]:
df.shape

(4, 3)

In [87]:
df.columns

Index(['Name', 'Age', 'Salary'], dtype='str')

In [88]:
df.rename(columns={'Salary': 'Monthly_Salary'})

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [89]:
df.rename(columns={'Salary': 'Monthly_Salary'}, inplace=True)

In [90]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [91]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      str
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [92]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   17.500000    60000.000000
std     1.290994    25819.888975
min    16.000000    30000.000000
25%    16.750000    45000.000000
50%    17.500000    60000.000000
75%    18.250000    75000.000000
max    19.000000    90000.000000

In [93]:
#3. Save and Load data from CSV

df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [94]:
df.to_csv('Test_data.csv')

In [95]:
df.to_csv('Test_data.csv', index=False) #export data frame

In [96]:
load_df = pd.read_csv('Test_data.csv') #import data frame
load_df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [97]:
#4. Rows & Columns - Selection

In [98]:
# select column
df[['Name', 'Monthly_Salary']]

       Name  Monthly_Salary
0    Madhav           90000
1  Vishakha           70000
2    Lalita           50000
3   Rishabh           30000

In [99]:
# Select rows
# loc - index name based
df.loc[df.Name=='Madhav']
df.loc[(df.Name=='Madhav') & (df.Monthly_Salary>=50000)]

     Name  Age  Monthly_Salary
0  Madhav   16           90000

In [103]:
df.loc[0:2]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000

In [ ]:
# iloc - index value based
# df.iloc[0]
df.iloc[0:2]        #[start:stop:step]

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000

In [ ]:
# filter dataframe

In [104]:
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [109]:
df['Age'] > 15

0    True
1    True
2    True
3    True
Name: Age, dtype: bool

In [ ]:
df[df['Age'] >= 18]   # getting true value only

      Name  Age  Monthly_Salary
2   Lalita   18           50000
3  Rishabh   19           30000

In [114]:
df_age_filter = df[df['Age'] >= 18]

In [115]:
df_age_filter

      Name  Age  Monthly_Salary
2   Lalita   18           50000
3  Rishabh   19           30000

In [118]:
df[(df['Age'] >= 18) & (df['Monthly_Salary'] >= 50000)]

     Name  Age  Monthly_Salary
2  Lalita   18           50000

In [119]:
df.where(df['Age'] >= 18)

      Name   Age  Monthly_Salary
0      NaN   NaN             NaN
1      NaN   NaN             NaN
2   Lalita  18.0         50000.0
3  Rishabh  19.0         30000.0

In [120]:
df.where(df['Age'] >= 18, other = 'Not Eligible')

           Name           Age Monthly_Salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        Lalita            18          50000
3       Rishabh            19          30000

In [123]:
#6. Rows and Columns - Operations (Add, Update, Delete)
df

       Name  Age  Monthly_Salary
0    Madhav   16           90000
1  Vishakha   17           70000
2    Lalita   18           50000
3   Rishabh   19           30000

In [124]:
# add new column
df['Team'] = ['CEO', 'HR', 'CTO', 'DA']
df

       Name  Age  Monthly_Salary Team
0    Madhav   16           90000  CEO
1  Vishakha   17           70000   HR
2    Lalita   18           50000  CTO
3   Rishabh   19           30000   DA

In [126]:
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0

In [127]:
# add new row
df.loc[len(df)] = ['ABC', 21, 21000, 'IT', 2000]
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0
4       ABC   21           21000   IT   2000.0

In [128]:
len(df)

5

In [129]:
# update value
df.loc[0, 'Monthly_Salary'] = 95000
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           95000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0
4       ABC   21           21000   IT   2000.0

In [133]:
#update value - using column value
df.loc[df.Name == 'Madhav', 'Monthly_Salary'] = 90000
df

       Name  Age  Monthly_Salary Team    Bonus   salary  Monthly_salary
0    Madhav   16           90000  CEO  18000.0  90000.0         90000.0
1  Vishakha   17           70000   HR  14000.0      NaN             NaN
2    Lalita   18           50000  CTO  10000.0      NaN             NaN
3   Rishabh   19           30000   DA   6000.0      NaN             NaN
4       ABC   21           21000   IT   2000.0      NaN             NaN

In [134]:
df

       Name  Age  Monthly_Salary Team    Bonus   salary  Monthly_salary
0    Madhav   16           90000  CEO  18000.0  90000.0         90000.0
1  Vishakha   17           70000   HR  14000.0      NaN             NaN
2    Lalita   18           50000  CTO  10000.0      NaN             NaN
3   Rishabh   19           30000   DA   6000.0      NaN             NaN
4       ABC   21           21000   IT   2000.0      NaN             NaN

In [136]:
# delete value - row and column values
df.drop(df[df.Name == 'ABC'].index)  #drop row, axis = 0

       Name  Age  Monthly_Salary Team    Bonus   salary  Monthly_salary
0    Madhav   16           90000  CEO  18000.0  90000.0         90000.0
1  Vishakha   17           70000   HR  14000.0      NaN             NaN
2    Lalita   18           50000  CTO  10000.0      NaN             NaN
3   Rishabh   19           30000   DA   6000.0      NaN             NaN

In [137]:
df[df.Name == 'ABC']

  Name  Age  Monthly_Salary Team   Bonus  salary  Monthly_salary
4  ABC   21           21000   IT  2000.0     NaN             NaN

In [138]:
df.drop('salary', axis=1)

       Name  Age  Monthly_Salary Team    Bonus  Monthly_salary
0    Madhav   16           90000  CEO  18000.0         90000.0
1  Vishakha   17           70000   HR  14000.0             NaN
2    Lalita   18           50000  CTO  10000.0             NaN
3   Rishabh   19           30000   DA   6000.0             NaN
4       ABC   21           21000   IT   2000.0             NaN

In [139]:
df.drop('Monthly_salary', axis=1)

       Name  Age  Monthly_Salary Team    Bonus   salary
0    Madhav   16           90000  CEO  18000.0  90000.0
1  Vishakha   17           70000   HR  14000.0      NaN
2    Lalita   18           50000  CTO  10000.0      NaN
3   Rishabh   19           30000   DA   6000.0      NaN
4       ABC   21           21000   IT   2000.0      NaN

In [140]:
df

       Name  Age  Monthly_Salary Team    Bonus   salary  Monthly_salary
0    Madhav   16           90000  CEO  18000.0  90000.0         90000.0
1  Vishakha   17           70000   HR  14000.0      NaN             NaN
2    Lalita   18           50000  CTO  10000.0      NaN             NaN
3   Rishabh   19           30000   DA   6000.0      NaN             NaN
4       ABC   21           21000   IT   2000.0      NaN             NaN

In [141]:
df = df.drop('Monthly_salary', axis=1)

In [142]:
df

       Name  Age  Monthly_Salary Team    Bonus   salary
0    Madhav   16           90000  CEO  18000.0  90000.0
1  Vishakha   17           70000   HR  14000.0      NaN
2    Lalita   18           50000  CTO  10000.0      NaN
3   Rishabh   19           30000   DA   6000.0      NaN
4       ABC   21           21000   IT   2000.0      NaN

In [143]:
df = df.drop('salary', axis=1)

In [144]:
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0
4       ABC   21           21000   IT   2000.0

In [145]:
df = df.drop(df[df.Name == 'ABC'].index)

In [146]:
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0

In [147]:
df

       Name  Age  Monthly_Salary Team    Bonus
0    Madhav   16           90000  CEO  18000.0
1  Vishakha   17           70000   HR  14000.0
2    Lalita   18           50000  CTO  10000.0
3   Rishabh   19           30000   DA   6000.0